apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
  namespace: bali-bank-config-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: bali-bank-config-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - image: tufinim/bali-admin:na
        name: admin
        ports:
        - containerPort: 8080
